deployment:
  tasks:
    - export DEPLOYPATH=/home/smmturk/public_html/
    - /usr/bin/rsync -av --delete --exclude=".git" --exclude=".cpanel.yml" --exclude="config.php" --chmod=D755,F644 ./ $DEPLOYPATH
